### ISSUE TITLE
Issue-swap, bridge and explorer

### ISSUE THREAD

**Issue by lunarforky-z** [lunarforky-z/lifi-sdk#2]
Automated Review Comments
Issues in .gitignore:
  - (2, 'Line exceeds 80 characters')
Issues in index.html:
  - (3, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in package.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (19, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (29, 'Hardcoded string found')
  - (30, 'Hardcoded string found')
Issues in public/vite.svg:
  - (2, 'Line exceeds 80 characters')
  - (2, 'Hardcoded string found')
Issues in src/App.tsx:
  - (3, 'Hardcoded string found')
  - (5, 'Line exceeds 80 characters')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
Issues in src/components/QuoteFetcher.tsx:
  - (2, 'Hardcoded string found')
Issues in src/components/WalletHeader.tsx:
  - (4, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (23, 'Hardcoded string found')
  - (27, 'Hardcoded string found')
  - (35, 'Hardcoded string found')
Issues in src/main.tsx:
  - (3, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
Issues in src/providers/WalletProvider.tsx:
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in src/setupLifi.ts:
  - (6, 'Line exceeds 80 characters')
  - (7, 'Line exceeds 80 characters')
  - (8, 'Line exceeds 80 characters')
  - (9, 'Line exceeds 80 characters')
  - (13, 'Line exceeds 80 characters')
  - (14, 'Line exceeds 80 characters')
  - (17, 'Line exceeds 80 characters')
  - (20, 'Line exceeds 80 characters')
  - (21, 'Line exceeds 80 characters')
Issues in tsconfig.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (8, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
  - (10, 'Hardcoded string found')
  - (11, 'Hardcoded string found')
  - (12, 'Hardcoded string found')
  - (13, 'Hardcoded string found')
  - (14, 'Hardcoded string found')
  - (15, 'Hardcoded string found')
  - (16, 'Hardcoded string found')
  - (17, 'Hardcoded string found')
  - (18, 'Hardcoded string found')
  - (20, 'Hardcoded string found')
  - (21, 'Hardcoded string found')
Issues in tsconfig.node.json:
  - (3, 'Hardcoded string found')
  - (4, 'Hardcoded string found')
  - (5, 'Hardcoded string found')
  - (6, 'Hardcoded string found')
  - (7, 'Hardcoded string found')
  - (9, 'Hardcoded string found')
Issues in vite.config.ts:
  - (3, 'Hardcoded string found')
  - (11, 'Hardcoded string found')

**Comment by hylcore-V** [comment]
I got it.
